name: Release Package

permissions:
  id-token: write # Required for OIDC
  contents: read
  repository-projects: write

on:
  push:
    branches:
      - release

env:
  NPM_TOKEN: ""

jobs:
  build-and-publish:
    permissions:
      id-token: write # Required for OIDC
      packages: write
      contents: write
      pull-requests: write
      issues: write
      repository-projects: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
      - name: Update npm
        run: npm install -g npm@latest
      - name: Installing dependencies
        run: ./.yarn/releases/yarn-1.22.19.cjs
      - name: Validating TypeScript
        run: ./.yarn/releases/yarn-1.22.19.cjs test:tsc
      - name: Building package
        run: ./.yarn/releases/yarn-1.22.19.cjs build
      - name: Publish
        run: npm publish --access public
