name: Release Package

permissions:
  repository-projects: write

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          token: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
      - uses: actions/setup-node@v3
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TAG_NAME: ${{github.event.release.tag_name}}
        run: ./scripts/publish.sh
